apiVersion: v1
kind: Service
metadata:
  name: weave-gitops-service-nodeport
  namespace: flux-system
spec:
  type: NodePort
  selector:
    app.kubernetes.io/instance: ww-gitops
  ports:
    - port: 9001
      targetPort: 9001
      nodePort: 30009
