# @format

apiVersion: v1
kind: Service
metadata:
  name: react
  labels:
    app: react
    namespace: default
spec:
  type: NodePort
  selector:
    app: react
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 30001
