# @format

# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  workflow_dispatch:
    inputs:
      image_version:
        required: true
        description: イメージバージョンを入力（1.x.x）

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"

      - name: Install dependencies
        run: npm install
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: upload-build-files
          path: |
            build

      - name: Display structure of current files
        run: |
          ls -R

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.REPOSITORY_OWNER }}
          password: ${{ secrets.REPOSITORY_PASS }}

      - name: Build Docker image and push to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/${{ github.REPOSITORY_OWNER }}/react:${{ github.event.inputs.image_version }}
